name: build-and-push

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Clone repo inside machine
          uses: actions/checkout@v4
        - name: Install node
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: "latest"
        - name: Run bun
          run: |
            bun install
            bun test

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Clone repo inside machine
              uses: actions/checkout@v4
            - name: Extract docker image metadata
              id: meta
              uses: docker/metadata-actions@v5
              with:
                images: ${{ vars.DOCKER_USERNAME }}/devops-api-3
            - name: Login DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Push image
              uses: docker/build-push-action@v6
              with:
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                annotations: ${{ steps.meta.outputs.annotations }}
                provenance: true
                sbom: true