name: Pullrequest Test

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo inside machine
        uses: actions/checkout@v4
      - name: Install node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Run bun
        run: |
          bun install
          bun test